<?php

namespace Database\Seeders;

use App\Models\State;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('states')->delete();

        $districts = [
            'Abim',
            'Adjumani',
            'Agago',
            'Alebtong',
            'Amolatar',
            'Amudat',
            'Amuria',
            'Amuru',
            'Apac',
            'Arua',
            'Budaka',
            'Bududa',
            'Bugiri',
            'Buhweju',
            'Buikwe',
            'Bukedea',
            'Bukomansimbi',
            'Bukwo',
            'Bulambuli',
            'Buliisa',
            'Bundibugyo',
            'Bunyangabu',
            'Bushenyi',
            'Busia',
            'Butaleja',
            'Butambala',
            'Butebo',
            'Buvuma',
            'Buyende',
            'Dokolo',
            'Gomba',
            'Gulu',
            'Hoima',
            'Ibanda',
            'Iganga',
            'Isingiro',
            'Jinja',
            'Kaabong',
            'Kabale',
            'Kabarole',
            'Kagadi',
            'Kakumiro',
            'Kalangala',
            'Kaliro',
            'Kalungu',
            'Kampala',
            'Kamuli',
            'Kamwenge',
            'Kanungu',
            'Kapchorwa',
            'Kapelebyong',
            'Kasanda',
            'Kasese',
            'Katakwi',
            'Kayunga',
            'Kibaale',
            'Kiboga',
            'Kibuku',
            'Kiruhura',
            'Kiryandongo',
            'Kisoro',
            'Kitgum',
            'Koboko',
            'Kole',
            'Kotido',
            'Kumi',
            'Kween',
            'Kyankwanzi',
            'Kyegegwa',
            'Kyenjojo',
            'Kyotera',
            'Lamwo',
            'Lira',
            'Luuka',
            'Luwero',
            'Lwengo',
            'Lyantonde',
            'Manafwa',
            'Maracha',
            'Masaka',
            'Masindi',
            'Mayuge',
            'Mbale',
            'Mbarara',
            'Mitooma',
            'Mityana',
            'Moroto',
            'Moyo',
            'Mpigi',
            'Mubende',
            'Mukono',
            'Nakapiripirit',
            'Nakaseke',
            'Nakasongola',
            'Namayingo',
            'Namisindwa',
            'Namutumba',
            'Napak',
            'Nebbi',
            'Ngora',
            'Ntoroko',
            'Ntungamo',
            'Nwoya',
            'Omoro',
            'Otuke',
            'Oyam',
            'Pader',
            'Pakwach',
            'Pallisa',
            'Rakai',
            'Rubanda',
            'Rubirizi',
            'Rukiga',
            'Rukungiri',
            'Sembabule',
            'Serere',
            'Sheema',
            'Sironko',
            'Soroti',
            'Tororo',
            'Wakiso',
            'Yumbe',
            'Zombo'
        ];


        foreach ($districts as $district) {
            State::create(['district' => $district]);
        }
    }
}
